version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - CI=true
      - REACT_APP_BACKEND_URL=https://api-stage.santiment.net
      - NODE_ENV=development
    command: npm run test
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - CI=true
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=https://api-stage.santiment.net
    expose:
      - 8000
    ports:
      - 8000:3000
    volumes:
      - ./:/opt
      - '/opt/node_modules'
    command: sh -c "npm start"
