version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - CI=true
      - REACT_APP_BACKEND_URL=https://api-stage.santiment.net
    command: yarn test --ci
  frontend:
    build: .
    environment:
      - REACT_APP_BACKEND_URL=https://api-stage.santiment.net
    expose:
      - 8000
    ports:
      - 8000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: /bin/bash -c "yarn start"
